/* ============================================================
   DataSciencePro.in — Project Data
   114+ projects across CSE, DS, AI/ML, EEE, ECE, Mech
   ============================================================ */

const PROJECTS = [

  /* ---- CSE / IT ---- */
  { id: 1,  branch:'cse', title:'AI-Powered Resume Analyzer & Job Matcher', domain:'NLP / AI', difficulty:'intermediate', type:'major', price:16000, techStack:['Python','spaCy','FastAPI','React'], duration:'6 weeks', teamSize:'2–3', desc:'Parses resumes, scores against job descriptions using NLP, and provides skill-gap analysis with improvement suggestions.' },
  { id: 2,  branch:'cse', title:'Blockchain-Based Certificate Verification System', domain:'Blockchain', difficulty:'advanced', type:'industry', price:24000, techStack:['Solidity','Ethereum','React','Node.js'], duration:'8 weeks', teamSize:'3', desc:'Immutable academic certificate storage and instant verification using Ethereum smart contracts and QR codes.' },
  { id: 3,  branch:'cse', title:'Real-Time Collaborative Code Editor', domain:'Web Development', difficulty:'intermediate', type:'major', price:14000, techStack:['Node.js','Socket.IO','Monaco Editor','React'], duration:'5 weeks', teamSize:'2–3', desc:'Multi-user code editor with real-time sync, syntax highlighting, chat, and session recording.' },
  { id: 4,  branch:'cse', title:'E-Commerce Product Recommendation Engine', domain:'ML / E-commerce', difficulty:'intermediate', type:'major', price:15000, techStack:['Python','Scikit-learn','Django','PostgreSQL'], duration:'6 weeks', teamSize:'2–3', desc:'Collaborative filtering and content-based recommendation system for an e-commerce platform with A/B testing dashboard.' },
  { id: 5,  branch:'cse', title:'Cyber Threat Intelligence Platform', domain:'Cybersecurity', difficulty:'advanced', type:'research', price:26000, techStack:['Python','ELK Stack','MITRE ATT&CK','React'], duration:'10 weeks', teamSize:'3–4', desc:'Aggregates threat feeds, correlates indicators of compromise, and visualises attack patterns using MITRE framework.' },
  { id: 6,  branch:'cse', title:'Hospital Management System with AI Triage', domain:'Healthcare IT', difficulty:'intermediate', type:'major', price:18000, techStack:['Python','Django','React','MySQL'], duration:'7 weeks', teamSize:'3', desc:'Full-stack hospital management with appointment booking, EMR, billing, and AI-based patient triage priority scoring.' },
  { id: 7,  branch:'cse', title:'URL Phishing Detection using Machine Learning', domain:'Cybersecurity / ML', difficulty:'beginner', type:'mini', price:8000, techStack:['Python','Scikit-learn','Flask','Bootstrap'], duration:'3 weeks', teamSize:'2', desc:'Classifies URLs as phishing or legitimate using feature engineering and ensemble ML models.' },
  { id: 8,  branch:'cse', title:'Distributed File Storage System (Mini IPFS)', domain:'Distributed Systems', difficulty:'advanced', type:'research', price:22000, techStack:['Go','gRPC','SQLite','React'], duration:'9 weeks', teamSize:'3', desc:'Peer-to-peer distributed file storage with content-addressable storage, deduplication, and fault tolerance.' },
  { id: 9,  branch:'cse', title:'Online Exam Proctoring System', domain:'EdTech', difficulty:'intermediate', type:'industry', price:20000, techStack:['Python','OpenCV','FastAPI','React'], duration:'7 weeks', teamSize:'3', desc:'AI-based online exam platform with face monitoring, tab-switch detection, and auto-flagging suspicious behaviour.' },
  { id: 10, branch:'cse', title:'Social Media Sentiment Dashboard', domain:'NLP / Analytics', difficulty:'beginner', type:'mini', price:9000, techStack:['Python','VADER','Streamlit','Twitter API'], duration:'3 weeks', teamSize:'1–2', desc:'Real-time Twitter sentiment analysis with interactive dashboard, word cloud, and trend tracking.' },
  { id: 11, branch:'cse', title:'Microservices E-Commerce Platform', domain:'Cloud / Backend', difficulty:'advanced', type:'industry', price:28000, techStack:['Docker','Kubernetes','Spring Boot','React'], duration:'10 weeks', teamSize:'3–4', desc:'Containerised e-commerce with separate microservices for auth, cart, orders, payments, and API gateway.' },
  { id: 12, branch:'cse', title:'Cloud Cost Optimisation Dashboard (FinOps)', domain:'Cloud Computing', difficulty:'intermediate', type:'industry', price:18000, techStack:['Python','Azure SDK','Power BI','FastAPI'], duration:'6 weeks', teamSize:'2–3', desc:'Tracks multi-cloud resource utilisation, identifies idle resources, and recommends cost-saving actions.' },
  { id: 13, branch:'cse', title:'Bug Tracking & Agile Project Management Tool', domain:'Web Development', difficulty:'intermediate', type:'major', price:14000, techStack:['React','Node.js','MongoDB','Socket.IO'], duration:'6 weeks', teamSize:'2–3', desc:'Full-featured Jira-like tool with sprint planning, Kanban board, burn-down charts, and Git integration.' },
  { id: 14, branch:'cse', title:'Network Intrusion Detection System', domain:'Cybersecurity / ML', difficulty:'advanced', type:'research', price:24000, techStack:['Python','Scikit-learn','Wireshark','Flask'], duration:'8 weeks', teamSize:'3', desc:'ML-based NIDS that classifies network traffic packets into attack categories using NSL-KDD and CICIDS datasets.' },
  { id: 15, branch:'cse', title:'Grocery Delivery App (Full Stack)', domain:'Mobile / Web', difficulty:'intermediate', type:'major', price:16000, techStack:['React Native','Node.js','MongoDB','Stripe'], duration:'7 weeks', teamSize:'3', desc:'End-to-end grocery app with real-time order tracking, vendor dashboard, payment gateway, and push notifications.' },
  { id: 16, branch:'cse', title:'Text Summarisation Tool using Transformers', domain:'NLP', difficulty:'intermediate', type:'mini', price:10000, techStack:['Python','HuggingFace','Streamlit','FastAPI'], duration:'4 weeks', teamSize:'2', desc:'Extractive and abstractive summarisation using BERT/T5 with comparison dashboard and readability scores.' },

  /* ---- Data Science ---- */
  { id: 20, branch:'ds', title:'Stock Market Prediction using LSTM', domain:'Finance / ML', difficulty:'intermediate', type:'major', price:15000, techStack:['Python','TensorFlow','Plotly','yFinance'], duration:'5–6 weeks', teamSize:'2', desc:'Predicts future stock prices using LSTM with live data fetching, interactive dashboard and backtesting module.' },
  { id: 21, branch:'ds', title:'Customer Churn Prediction Platform', domain:'CRM / Analytics', difficulty:'intermediate', type:'industry', price:17000, techStack:['Python','XGBoost','SHAP','Streamlit'], duration:'6 weeks', teamSize:'2–3', desc:'Predicts which customers will churn, explains predictions with SHAP values, and recommends retention strategies.' },
  { id: 22, branch:'ds', title:'COVID-19 Data Analysis & Forecasting Dashboard', domain:'Public Health / Analytics', difficulty:'beginner', type:'mini', price:8000, techStack:['Python','Pandas','Plotly','Prophet'], duration:'3 weeks', teamSize:'1–2', desc:'Interactive global COVID-19 dashboard with trend analysis, peak prediction, and vaccination progress tracker.' },
  { id: 23, branch:'ds', title:'Real Estate Price Prediction & Market Analysis', domain:'Finance / ML', difficulty:'intermediate', type:'major', price:14000, techStack:['Python','Scikit-learn','GeoPandas','Dash'], duration:'5 weeks', teamSize:'2', desc:'Predicts house prices using ensemble models with geospatial visualisation and market trend analysis.' },
  { id: 24, branch:'ds', title:'Crop Yield Prediction for Smart Agriculture', domain:'AgriTech', difficulty:'intermediate', type:'research', price:16000, techStack:['Python','Random Forest','Streamlit','OpenWeather API'], duration:'6 weeks', teamSize:'2–3', desc:'Predicts crop yield based on soil, weather, and historical data with interactive recommendation dashboard.' },
  { id: 25, branch:'ds', title:'Sales Forecasting & Inventory Optimisation', domain:'Retail Analytics', difficulty:'intermediate', type:'industry', price:18000, techStack:['Python','Prophet','SQL','Power BI'], duration:'6 weeks', teamSize:'2–3', desc:'Time-series forecasting for retail sales with automatic inventory reorder recommendations and Power BI dashboard.' },
  { id: 26, branch:'ds', title:'Healthcare Readmission Prediction (MIMIC Dataset)', domain:'Healthcare Analytics', difficulty:'advanced', type:'research', price:22000, techStack:['Python','LightGBM','SHAP','Pandas'], duration:'8 weeks', teamSize:'2–3', desc:'Predicts 30-day hospital readmission using MIMIC-III clinical dataset with fairness analysis and model explainability.' },
  { id: 27, branch:'ds', title:'Fraud Detection in Financial Transactions', domain:'FinTech', difficulty:'advanced', type:'industry', price:21000, techStack:['Python','Isolation Forest','Kafka','MongoDB'], duration:'7 weeks', teamSize:'3', desc:'Real-time fraud detection using anomaly detection algorithms on streaming transaction data with alerting pipeline.' },
  { id: 28, branch:'ds', title:'Twitter Trend Analysis & Viral Topic Prediction', domain:'Social Media Analytics', difficulty:'intermediate', type:'major', price:13000, techStack:['Python','NLP','NetworkX','Plotly'], duration:'5 weeks', teamSize:'2', desc:'Analyses Twitter trends, detects emerging viral topics, and models information diffusion through network graphs.' },
  { id: 29, branch:'ds', title:'Energy Consumption Forecasting (Smart Meter)', domain:'Energy Analytics', difficulty:'intermediate', type:'major', price:15000, techStack:['Python','ARIMA','LSTM','Streamlit'], duration:'5 weeks', teamSize:'2', desc:'Forecasts household energy consumption from smart meter data with anomaly detection and cost savings alerts.' },
  { id: 30, branch:'ds', title:'Supply Chain Risk Analytics Dashboard', domain:'Logistics / Analytics', difficulty:'advanced', type:'industry', price:24000, techStack:['Python','Neo4j','D3.js','FastAPI'], duration:'8 weeks', teamSize:'3', desc:'Models supply chain as a graph, identifies bottlenecks and risk nodes, simulates disruptions and recovery paths.' },
  { id: 31, branch:'ds', title:'E-Learning Content Recommendation System', domain:'EdTech', difficulty:'intermediate', type:'major', price:14000, techStack:['Python','Collaborative Filtering','Django','React'], duration:'5 weeks', teamSize:'2–3', desc:'Personalised course recommendation engine with knowledge graph and adaptive learning path generation.' },

  /* ---- AI / ML ---- */
  { id: 40, branch:'aiml', title:'Real-Time Face Recognition Attendance System', domain:'Computer Vision', difficulty:'advanced', type:'major', price:18000, techStack:['Python','OpenCV','DeepFace','Flask'], duration:'6–8 weeks', teamSize:'2–3', desc:'Automated attendance using deep learning face recognition with real-time camera feed and Excel export.' },
  { id: 41, branch:'aiml', title:'Medical Image Segmentation (Brain Tumour)', domain:'Medical AI', difficulty:'advanced', type:'research', price:26000, techStack:['Python','PyTorch','U-Net','Streamlit'], duration:'10 weeks', teamSize:'3', desc:'Semantic segmentation of brain MRI scans using U-Net architecture with DICE score evaluation and overlay visualisation.' },
  { id: 42, branch:'aiml', title:'Generative AI Chatbot with RAG (Custom Domain)', domain:'GenAI / NLP', difficulty:'advanced', type:'industry', price:28000, techStack:['Python','LangChain','FAISS','FastAPI'], duration:'8 weeks', teamSize:'2–3', desc:'Domain-specific chatbot using Retrieval-Augmented Generation with custom knowledge base, chat history, and evaluation.' },
  { id: 43, branch:'aiml', title:'Autonomous Vehicle Lane Detection System', domain:'Computer Vision', difficulty:'advanced', type:'research', price:24000, techStack:['Python','OpenCV','YOLO','TensorFlow'], duration:'9 weeks', teamSize:'3', desc:'Real-time lane detection and vehicle tracking pipeline for autonomous driving using YOLO and OpenCV.' },
  { id: 44, branch:'aiml', title:'Emotion Recognition from Speech Audio', domain:'Speech AI', difficulty:'intermediate', type:'major', price:17000, techStack:['Python','LibROSA','CNN','Flask'], duration:'6 weeks', teamSize:'2', desc:'Classifies emotions (happy, sad, angry, neutral) from audio using MFCC features and convolutional neural networks.' },
  { id: 45, branch:'aiml', title:'Plant Disease Detection using CNN', domain:'AgriTech / Computer Vision', difficulty:'intermediate', type:'major', price:15000, techStack:['Python','TensorFlow','MobileNet','Streamlit'], duration:'5 weeks', teamSize:'2', desc:'Identifies 38+ plant diseases from leaf images using transfer learning with 97%+ accuracy and remedy suggestions.' },
  { id: 46, branch:'aiml', title:'Object Detection & Counting for Retail (YOLO)', domain:'Computer Vision / Retail', difficulty:'advanced', type:'industry', price:22000, techStack:['Python','YOLOv8','FastAPI','React'], duration:'7 weeks', teamSize:'2–3', desc:'Real-time product detection, shelf gap analysis, and footfall counting using YOLOv8 for retail analytics.' },
  { id: 47, branch:'aiml', title:'AI News Fact-Checker using NLP', domain:'NLP / Media', difficulty:'intermediate', type:'research', price:18000, techStack:['Python','BERT','Flask','React'], duration:'6 weeks', teamSize:'2–3', desc:'Automatically classifies news articles as real or fake using fine-tuned BERT with explainability and source tracing.' },
  { id: 48, branch:'aiml', title:'Sign Language Recognition System', domain:'Computer Vision / Accessibility', difficulty:'advanced', type:'research', price:22000, techStack:['Python','MediaPipe','LSTM','Streamlit'], duration:'8 weeks', teamSize:'2–3', desc:'Translates hand gestures to text in real-time using MediaPipe landmarks and bidirectional LSTM classifier.' },
  { id: 49, branch:'aiml', title:'AI-Powered Code Review Bot', domain:'Developer Tools / AI', difficulty:'advanced', type:'industry', price:25000, techStack:['Python','GPT API','GitHub Actions','FastAPI'], duration:'7 weeks', teamSize:'2–3', desc:'Automated code review bot that spots bugs, suggests improvements, and enforces style guides via GitHub PR comments.' },
  { id: 50, branch:'aiml', title:'Document Layout Analysis & OCR Pipeline', domain:'Document AI', difficulty:'intermediate', type:'industry', price:19000, techStack:['Python','Tesseract','LayoutParser','FastAPI'], duration:'6 weeks', teamSize:'2', desc:'Extracts structured data from scanned documents including tables, forms, and handwritten text with 95%+ accuracy.' },
  { id: 51, branch:'aiml', title:'Personalized Music Recommendation using Deep Learning', domain:'RecSys / Music', difficulty:'intermediate', type:'major', price:16000, techStack:['Python','Keras','Spotify API','React'], duration:'6 weeks', teamSize:'2–3', desc:'Recommends music based on audio features and listening history using autoencoders and collaborative filtering.' },
  { id: 52, branch:'aiml', title:'AI Traffic Management System (Simulation)', domain:'Smart City / CV', difficulty:'advanced', type:'research', price:26000, techStack:['Python','SUMO','YOLO','OpenCV'], duration:'10 weeks', teamSize:'3–4', desc:'Adaptive traffic signal control using vehicle count from YOLO detection with SUMO traffic simulation integration.' },

  /* ---- EEE ---- */
  { id: 60, branch:'eee', title:'Smart Grid Energy Management System', domain:'Power Systems', difficulty:'advanced', type:'research', price:25000, techStack:['MATLAB','Python','Arduino','SCADA'], duration:'8 weeks', teamSize:'3', desc:'MATLAB-based smart grid simulation with load forecasting, fault detection and renewable energy integration.' },
  { id: 61, branch:'eee', title:'Solar MPPT Controller Design & Simulation', domain:'Renewable Energy', difficulty:'intermediate', type:'major', price:16000, techStack:['MATLAB Simulink','Python','Arduino'], duration:'6 weeks', teamSize:'2–3', desc:'Designs and simulates Perturb & Observe and Incremental Conductance MPPT algorithms with hardware prototype.' },
  { id: 62, branch:'eee', title:'Power Quality Analyser with Harmonic Detection', domain:'Power Electronics', difficulty:'advanced', type:'research', price:22000, techStack:['MATLAB','LabVIEW','Arduino','Python'], duration:'8 weeks', teamSize:'3', desc:'Real-time power quality monitoring with THD measurement, harmonic spectrum analysis, and compensation strategies.' },
  { id: 63, branch:'eee', title:'EV Battery Management System (BMS)', domain:'Electric Vehicles', difficulty:'advanced', type:'industry', price:28000, techStack:['MATLAB Simulink','Arduino','Python','CAN Bus'], duration:'10 weeks', teamSize:'3–4', desc:'State of charge/health estimation, cell balancing, thermal management and fault protection for Li-ion packs.' },
  { id: 64, branch:'eee', title:'Grid-Tied Inverter Design using SPWM', domain:'Power Electronics', difficulty:'intermediate', type:'major', price:18000, techStack:['MATLAB Simulink','PSIM','Python'], duration:'6 weeks', teamSize:'2–3', desc:'Single-phase grid-tied inverter with SPWM control, power factor correction, and IEEE 1547 compliance analysis.' },
  { id: 65, branch:'eee', title:'Fault Detection in Induction Motor using ML', domain:'Condition Monitoring', difficulty:'intermediate', type:'research', price:19000, techStack:['Python','MATLAB','Scikit-learn','Arduino'], duration:'7 weeks', teamSize:'2–3', desc:'Detects bearing faults, rotor eccentricity, and winding faults from vibration signals using CNN and SVM classifiers.' },
  { id: 66, branch:'eee', title:'Microgrid Energy Storage Optimisation', domain:'Energy Storage', difficulty:'advanced', type:'research', price:24000, techStack:['MATLAB','Python','CPLEX','Simulink'], duration:'9 weeks', teamSize:'3', desc:'Optimal scheduling of battery storage and renewable sources in an islanded microgrid using linear programming.' },
  { id: 67, branch:'eee', title:'Smart Street Lighting with Energy Monitoring', domain:'Smart City / IoT', difficulty:'beginner', type:'mini', price:9000, techStack:['Arduino','ESP8266','MATLAB','Blynk'], duration:'4 weeks', teamSize:'2', desc:'Automatic intensity control based on ambient light and motion with energy consumption monitoring dashboard.' },
  { id: 68, branch:'eee', title:'Wireless Power Transfer System (Resonant)', domain:'Power Electronics', difficulty:'advanced', type:'research', price:22000, techStack:['MATLAB Simulink','COMSOL','Python'], duration:'8 weeks', teamSize:'3', desc:'Designs and simulates magnetically resonant wireless power transfer with efficiency optimisation and SAR analysis.' },
  { id: 69, branch:'eee', title:'Power System Stability Analysis (FACTS Devices)', domain:'Power Systems', difficulty:'advanced', type:'research', price:24000, techStack:['MATLAB','PowerWorld','Python'], duration:'8 weeks', teamSize:'3', desc:'Voltage stability and transient stability analysis with SVC/STATCOM placement optimisation using PSAT.' },

  /* ---- ECE ---- */
  { id: 80, branch:'ece', title:'IoT-Based Smart Home Automation System', domain:'IoT / Embedded', difficulty:'intermediate', type:'major', price:20000, techStack:['ESP32','MQTT','Flutter','Firebase'], duration:'7 weeks', teamSize:'2–3', desc:'ESP32-based home automation with voice control, mobile app, energy monitoring, and Alexa integration.' },
  { id: 81, branch:'ece', title:'5G Channel Estimation using Deep Learning', domain:'Wireless Communication', difficulty:'advanced', type:'research', price:26000, techStack:['Python','MATLAB','TensorFlow','GNU Radio'], duration:'10 weeks', teamSize:'3', desc:'DNN-based OFDM channel estimation for 5G NR with comparison against traditional LS and MMSE estimators.' },
  { id: 82, branch:'ece', title:'VLSI Design of Low-Power ALU (FPGA)', domain:'VLSI / Digital Design', difficulty:'advanced', type:'major', price:22000, techStack:['Verilog','Xilinx Vivado','ModelSim','Python'], duration:'8 weeks', teamSize:'2–3', desc:'Low-power 16-bit ALU design using clock gating and dual-rail logic, synthesised and tested on Xilinx FPGA.' },
  { id: 83, branch:'ece', title:'Software Defined Radio (SDR) Signal Analyser', domain:'RF / Communications', difficulty:'advanced', type:'research', price:24000, techStack:['GNU Radio','Python','RTL-SDR','MATLAB'], duration:'9 weeks', teamSize:'3', desc:'FM demodulation, spectrum analysis, and AM/FM/SSB receiver implementation using RTL-SDR and GNU Radio.' },
  { id: 84, branch:'ece', title:'Wearable ECG Monitor with Arrhythmia Detection', domain:'Biomedical Electronics', difficulty:'advanced', type:'industry', price:26000, techStack:['Arduino','Python','TensorFlow','Bluetooth LE'], duration:'9 weeks', teamSize:'3', desc:'AD8232-based ECG acquisition, BLE transmission to mobile app, and ML-based arrhythmia classification.' },
  { id: 85, branch:'ece', title:'Radar-Based Gesture Recognition System', domain:'Radar / ML', difficulty:'advanced', type:'research', price:25000, techStack:['Python','MATLAB','TensorFlow','BGT60TR13C'], duration:'9 weeks', teamSize:'3', desc:'Millimetre-wave radar gesture recognition using micro-Doppler signatures and CNN classification.' },
  { id: 86, branch:'ece', title:'UAV Path Planning with Obstacle Avoidance', domain:'Drones / Robotics', difficulty:'advanced', type:'research', price:28000, techStack:['Python','ROS','MATLAB','Gazebo'], duration:'10 weeks', teamSize:'3–4', desc:'A* and RRT*-based UAV path planning with dynamic obstacle avoidance, simulated in Gazebo with ROS.' },
  { id: 87, branch:'ece', title:'Smart Parking System using Computer Vision', domain:'Computer Vision / IoT', difficulty:'intermediate', type:'major', price:18000, techStack:['Python','OpenCV','ESP32','Firebase'], duration:'6 weeks', teamSize:'2–3', desc:'Detects vacant parking slots from CCTV feed using OpenCV, updates availability on mobile app in real time.' },
  { id: 88, branch:'ece', title:'LoRaWAN-Based Environmental Monitoring Network', domain:'IoT / Wireless', difficulty:'intermediate', type:'research', price:20000, techStack:['Arduino','LoRa','Python','Grafana'], duration:'7 weeks', teamSize:'2–3', desc:'Long-range IoT sensor network for temperature, humidity, PM2.5, and CO2 monitoring with cloud dashboard.' },
  { id: 89, branch:'ece', title:'OFDM Transceiver Simulation with Channel Coding', domain:'Digital Communications', difficulty:'intermediate', type:'major', price:16000, techStack:['MATLAB','Python','GNU Radio'], duration:'6 weeks', teamSize:'2', desc:'Full OFDM transceiver with LDPC coding, pilot-based channel estimation, and BER analysis across AWGN/Rayleigh.' },

  /* ---- Mechanical ---- */
  { id: 100, branch:'mech', title:'Autonomous Line-Following Robot with Obstacle Avoidance', domain:'Robotics', difficulty:'advanced', type:'major', price:22000, techStack:['Arduino','C++','Python','ROS'], duration:'8–10 weeks', teamSize:'3–4', desc:'Arduino-based autonomous robot with PID control, ultrasonic obstacle avoidance, and telemetry dashboard.' },
  { id: 101, branch:'mech', title:'CFD Analysis of Airfoil using ANSYS Fluent', domain:'Fluid Mechanics / CFD', difficulty:'advanced', type:'research', price:22000, techStack:['ANSYS Fluent','Python','MATLAB'], duration:'8 weeks', teamSize:'2–3', desc:'Aerodynamic analysis of NACA airfoils at various AOAs with pressure, velocity, and lift/drag coefficient plots.' },
  { id: 102, branch:'mech', title:'Industry 4.0 Predictive Maintenance System', domain:'Manufacturing / ML', difficulty:'advanced', type:'industry', price:26000, techStack:['Python','Scikit-learn','OPC-UA','React'], duration:'9 weeks', teamSize:'3', desc:'Vibration sensor data pipeline with anomaly detection to predict machine failures before they occur.' },
  { id: 103, branch:'mech', title:'3D-Printed Prosthetic Hand with EMG Control', domain:'Biomedical / Robotics', difficulty:'advanced', type:'research', price:28000, techStack:['Arduino','Python','SOLIDWORKS','3D Printing'], duration:'10 weeks', teamSize:'3–4', desc:'EMG-controlled 3D-printed prosthetic hand with gesture classification using ML and servo actuation.' },
  { id: 104, branch:'mech', title:'Solar Water Heater System Design & Analysis', domain:'Thermal Engineering', difficulty:'intermediate', type:'major', price:14000, techStack:['MATLAB','ANSYS','Python','Excel'], duration:'5 weeks', teamSize:'2', desc:'Design, thermal analysis, and performance simulation of flat-plate solar water heating system with cost payback study.' },
  { id: 105, branch:'mech', title:'Automated Material Handling with PLC & SCADA', domain:'Automation / PLC', difficulty:'intermediate', type:'industry', price:20000, techStack:['Siemens TIA Portal','WinCC','Python','OPC-UA'], duration:'7 weeks', teamSize:'2–3', desc:'Conveyor belt material sorting automation using PLC ladder logic with SCADA HMI and production KPI dashboard.' },
  { id: 106, branch:'mech', title:'Vibration Analysis of Rotating Machinery (FFT)', domain:'Condition Monitoring', difficulty:'intermediate', type:'major', price:16000, techStack:['MATLAB','Python','LabVIEW','Arduino'], duration:'6 weeks', teamSize:'2–3', desc:'Acquires vibration data from accelerometers, performs FFT and spectrum analysis, detects imbalance and misalignment.' },
  { id: 107, branch:'mech', title:'Exoskeleton Arm Design for Rehabilitation', domain:'Biomedical / Robotics', difficulty:'advanced', type:'research', price:28000, techStack:['SOLIDWORKS','MATLAB','Arduino','Python'], duration:'10 weeks', teamSize:'3–4', desc:'Kinematic and dynamic analysis of an upper-limb exoskeleton with EMG-based intent detection and control algorithm.' },
  { id: 108, branch:'mech', title:'Green Building Energy Audit & Optimisation', domain:'Energy / Thermal', difficulty:'intermediate', type:'major', price:15000, techStack:['Python','EnergyPlus','MATLAB','Excel'], duration:'6 weeks', teamSize:'2', desc:'Energy simulation of a commercial building using EnergyPlus with HVAC optimisation and ECBC compliance check.' },
  { id: 109, branch:'mech', title:'Finite Element Analysis of Structural Components', domain:'FEA / Structural', difficulty:'intermediate', type:'major', price:14000, techStack:['ANSYS Mechanical','Python','MATLAB'], duration:'5 weeks', teamSize:'2', desc:'Static and modal FEA of chassis/frame components with mesh sensitivity analysis and safety factor optimisation.' },

];
